# Generated by Django 5.1 on 2024-09-03 10:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="appointment",
            options={
                "verbose_name": "Appointment",
                "verbose_name_plural": "Appointments",
            },
        ),
        migrations.AlterUniqueTogether(
            name="appointment",
            unique_together={("doctor", "scheduled_at")},
        ),
    ]
