# Generated by Django 5.1.1 on 2024-09-10 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_alter_appointment_options_appointment_status'),
        ('appointments', '0004_appointment_appointment_doctor__649ad1_idx_and_more'),
    ]

    operations = [
    ]
