# Generated by Django 5.1 on 2024-09-02 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_initial'),
        ('medical_records', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='appointment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointments.appointment'),
        ),
    ]
