# Generated by Django 5.1 on 2024-09-02 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0002_initial"),
        ("medical_records", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicalrecord",
            name="appointment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="appointments.appointment",
            ),
        ),
        migrations.AlterField(
            model_name="medicalrecord",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="medicalrecord",
            name="notes",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="medicalrecord",
            name="report",
            field=models.FileField(blank=True, null=True, upload_to="medical_records/"),
        ),
    ]
